sudo: required
dist: xenial

language: ruby
cache: bundler

if: tag IS blank

env:
  global:
    - CI_NODE_TOTAL=15
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4
    - CI_NODE_INDEX=5
    - CI_NODE_INDEX=6
    - CI_NODE_INDEX=7
    - CI_NODE_INDEX=8
    - CI_NODE_INDEX=9
    - CI_NODE_INDEX=10
    - CI_NODE_INDEX=11
    - CI_NODE_INDEX=12
    - CI_NODE_INDEX=13
    - CI_NODE_INDEX=14

services:
  - mysql
  - redis
  - memcached

before_install:
  - bash script/travis_ebook_converters.sh

before_script:
  - bash script/travis_configure.sh
  - bash script/travis_elasticsearch_upgrade.sh
  - bash script/travis_multiple_redis.sh
  - bash script/travis_mysql.sh
  - RAILS_ENV=test bundle exec rake db:schema:load 
  - RAILS_ENV=test bundle exec rake db:migrate

script:
  - bundle exec cucumber features
  - bundle exec rspec spec
