language: ruby
cache: bundler
sudo: required
env:
  - TEST_GROUP="cucumber -r features features/other_a            -f Ao3Cucumber::Formatter --color"
rvm:
  - "2.2.5"
services:
  - elasticsearch
  - redis-server
  - memcached
script:
  - rm -f structure.sql
  - RAILS_ENV=test bundle exec rake db:create:all --trace
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - travis_retry bundle exec $TEST_GROUP
before_script:
  - bash script/travis_configure.sh
  - bash script/travis_elasticsearch_upgrade.sh
notifications:
  email:
    recipients:
      - otw-coders-extra@transformativeworks.org
    on_success: change
    on_failure: always
  irc:
   channels:
     - "irc.freenode.org#otw-dev"
   on_success: change
   on_failure: change
addons:
  browserstack:
    username: "jamesbeal1"
    access_key:
      secure: "R/ibAEHJaCx9xe9mHPT3Kp5qX50Lca64BlOse4nYns8OvKjlH5gdoBvbFtQxz5/XN4sUqXU5s79v15HHlLbP2MGe/yN5vv/t/iBGA4mFT5T/ZiAJ1D6yBgcWff6RD49s04Nn2wVtvURvHv0NKjtn807escvzpF+y/jT1ysuWtFo="
